# Generated by Django 3.1.2 on 2020-11-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productosApp', '0002_auto_20201108_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='autor',
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=255)),
                ('whatsapp_link', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(upload_to='fototd')),
                ('foto_fondo', models.ImageField(upload_to='fototd')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productosApp.tienda'),
            preserve_default=False,
        ),
    ]
