# Generated by Django 3.1.2 on 2020-11-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0005_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='productosApp.tienda'),
            preserve_default=False,
        ),
    ]
