# Generated by Django 3.1.2 on 2020-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0007_pedido_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorian',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
