# Generated by Django 3.1.2 on 2020-12-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0009_auto_20201228_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen1',
            new_name='imagen',
        ),
    ]
