# Generated by Django 3.1.2 on 2020-12-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0012_auto_20201228_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, default='proyectoApp/static/images/images.png', upload_to='fotopr'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, default='proyectoApp/static/images/images.png', upload_to='fotopr'),
        ),
    ]
