# Generated by Django 3.1.2 on 2021-01-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0016_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
