# Generated by Django 3.1.2 on 2021-01-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0017_auto_20210107_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='facebook_post',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='instagram_post',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
