# Generated by Django 3.1.2 on 2021-01-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0019_auto_20210107_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
