# Generated by Django 3.1.2 on 2021-01-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0020_remove_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
