# Generated by Django 3.1.2 on 2021-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0021_tienda_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
