# Generated by Django 3.1.2 on 2021-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0023_auto_20210117_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tr',
            field=models.IntegerField(default=0),
        ),
    ]
