# Generated by Django 3.1.2 on 2021-01-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0024_auto_20210117_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pr',
            field=models.IntegerField(default=0),
        ),
    ]
