# Generated by Django 3.1.2 on 2021-01-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0025_producto_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pr',
            field=models.FloatField(default=0),
        ),
    ]
