# Generated by Django 3.1.2 on 2021-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0026_auto_20210117_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='url',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
