# Generated by Django 3.1.2 on 2021-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0027_tienda_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=models.CharField(max_length=1000),
        ),
    ]
