# Generated by Django 3.1.2 on 2021-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0028_auto_20210118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
    ]
