# Generated by Django 3.1.2 on 2021-01-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0029_auto_20210118_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
