# Generated by Django 3.1.2 on 2021-02-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0031_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='updated',
        ),
    ]
